# Generated by Django 4.2.3 on 2023-07-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('have_travel_partners', models.CharField(max_length=5)),
                ('accommodation', models.CharField(max_length=15)),
                ('next_destination', models.CharField(max_length=200)),
            ],
        ),
    ]
